# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zia.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(859, 510)
        self.bgimg = QtWidgets.QLabel(Dialog)
        self.bgimg.setGeometry(QtCore.QRect(-10, -50, 871, 561))
        self.bgimg.setText("")
        self.bgimg.setPixmap(QtGui.QPixmap('UIassets\\bg3.jpg'))
        self.bgimg.setScaledContents(True)
        self.bgimg.setObjectName("bgimg")
        self.gif = QtWidgets.QLabel(Dialog)
        self.gif.setGeometry(QtCore.QRect(30, 80, 391, 291))
        self.gif.setText("")
        self.gif.setPixmap(QtGui.QPixmap('UIassets\\wave-sound-unscreen.gif'))
        self.gif.setScaledContents(True)
        self.gif.setObjectName("gif")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 230, 61, 31))
        self.label.setObjectName("label")
        self.zia = QtWidgets.QTextBrowser(Dialog)
        self.zia.setGeometry(QtCore.QRect(160, 200, 131, 61))
        self.zia.setStyleSheet("background-color:transparent;\n"
"border:none;")
        self.zia.setObjectName("zia")
        self.micgif = QtWidgets.QLabel(Dialog)
        self.micgif.setGeometry(QtCore.QRect(30, 290, 401, 301))
        self.micgif.setText("")
        self.micgif.setPixmap(QtGui.QPixmap('UIassets\\mic1-unscreen.gif'))
        self.micgif.setScaledContents(True)
        self.micgif.setObjectName("micgif")
        self.phn_no = QtWidgets.QLineEdit(Dialog)
        self.phn_no.setGeometry(QtCore.QRect(568, 450, 271, 40))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.phn_no.setFont(font)
        self.phn_no.setStyleSheet("\n"
"QLineEdit{\n"
"border:3px solid rgb(79, 112, 237); \n"
"border-radius:20px;\n"
"color:rgb(159, 159, 159);\n"
"padding-left:40px;\n"
"padding-bottom:5px;\n"
"    background-color: rgb(0, 28, 49)\n"
"\n"
"}")
        self.phn_no.setText("")
        self.phn_no.setObjectName("phn_no")
        self.display = QtWidgets.QLabel(Dialog)
        self.display.setGeometry(QtCore.QRect(540, 270, 321, 161))
        self.display.setText("")
        self.display.setPixmap(QtGui.QPixmap('UIassets\\uicell-removebg-preview.png'))
        self.display.setScaledContents(True)
        self.display.setObjectName("display")
        self.dis_output = QtWidgets.QTextBrowser(Dialog)
        self.dis_output.setGeometry(QtCore.QRect(580, 300, 241, 101))
        self.dis_output.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"color:rgb(0, 213, 254);\n"
"border-radius:none;")
        self.dis_output.setObjectName("dis_output")
        self.start_push = QtWidgets.QPushButton(Dialog)
        self.start_push.setGeometry(QtCore.QRect(193, 419, 75, 30))
        self.start_push.setStyleSheet("background-color:transparent;")
        self.start_push.setText("")
        self.start_push.setObjectName("start_push")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.zia.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">ZIA</span></p></body></html>"))
        self.phn_no.setPlaceholderText(_translate("Dialog", "Input"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
